server:
  port: 9093
spring:
  application:
    name: doctor-service
  datasource:
    url: jdbc:mysql://localhost:3306/salamdb
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  kafka:
    bootstrap-servers: localhost:9092
eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka/
keycloak:
  auth-server-url: http://localhost:8080/
  realm: hms-realm
  resource: doctor-service
  public-client: true
  bearer-only: true
