server:
  port: 9091

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        server:
          webflux:
            locator:
              enabled: true
      routes:
        - id: patient-service
          uri: http://localhost:9092
          predicates:
            - Path=/patients/**
        - id: doctor-service
          uri: http://localhost:9093
          predicates:
            - Path=/doctors/**
eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka/
